name: Test
on:
  push:
    branches:
      - main
      - master
jobs:
  Try:
    runs-on: windows-2019
    steps:
      - uses: microsoft/setup-msbuild@v1.1
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.*'
          include-prerelease: true
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build
        run: msbuild ConsoleTestGetAssemblyAttributes.sln -restore
      - name: Run the app
        run: .\bin\Debug\net6.0\ConsoleTestGetAssemblyAttributes.exe
